import type { Metadata } from "next";
import { IBM_Plex_Mono, Quicksand } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Vertically Aligned",
  description: "Generated by create next app",
};

const quicksand = Quicksand({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-quicksand",
});

const ibm = IBM_Plex_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-ibm",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        /* className={inter.className}  */ className={`${quicksand.variable} ${ibm.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
